### PR TITLE
Close #27 New interface RenderEngine

### LINKED ISSUE #27: Craete interface RenderEngine

### PR DESCRIPTION
**Pull request by Abergard**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/50)

### CODE REVIEW

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-:-KjsUH76FBOBX688q3dc:bnfp4nl)*

**Comment by kn65op** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/graphics/RenderId.hpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-KjsbwutxGrS_JrN_cO4:-Kjsbwuuasa37Y1eTEed:bgy9752) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/bb70d57ebe394853657bc27880547f64c98bf10c/src/graphics/RenderId.hpp#L7)):*
> std::uint32_t
Why not integer, shouldn't we use integer almost always?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50)*

**Comment by kn65op** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50)*

**Comment by lukasz-m-maciejewski** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-:-KjsnqjI2HKO7VGvQJ8G:bnfp4nl)*

**Comment by kn65op** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/graphics/RenderId.hpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-KjsbwutxGrS_JrN_cO4:-KkN1bDqqrQPiBsHVoc-:bsfoypf) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/bb70d57ebe394853657bc27880547f64c98bf10c/src/graphics/RenderId.hpp#L7)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

> std::uint32_t
Why not integer, shouldn't we use integer almost always?
</blockquote></details>

Why shouldn't we use integer. There will be no calculation. I use unsigned because I need positive values only. Moreover with unsigned value the range will be wider.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/graphics/RenderId.hpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-KjsbwutxGrS_JrN_cO4:-Kkg7lPWLEbHP5mom6kM:b-q0su5f) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/bb70d57ebe394853657bc27880547f64c98bf10c/src/graphics/RenderId.hpp#L7)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why shouldn't we use integer. There will be no calculation. I use unsigned because I need positive values only. Moreover with unsigned value the range will be wider.
</blockquote></details>

OK, I don't expect we exceed 2147483647 objects ;]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50)*

**Comment by kn65op** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/50#-:-Kkg7szg7XjIhTgo4Zt3:bg7igk9)*

**Pull request merged**
