### PR TITLE
Td/issue30

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/68)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 1 of 9 files at r2, 1 of 7 files at r4, 7 of 13 files at r6, 4 of 10 files at r7, 2 of 2 files at r8, 4 of 7 files at r9.
Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/uml_src/class_diagram.uml, line 62 at r7](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L-bfZGJcwDP1xrc5aWV:-L-bfZGK6hFd7_GQLIqu:b-irl1h6) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/02faf9dad424ff1a2134da19ee2104be879015b5/docs/uml_src/class_diagram.uml#L62)):*
> ```
> + RenderId register_rendarable(const math::vec2d&, const math:::vec2d&)
> + RenderId register_background(const math::vec2d&)
> }
> ```

I'm not sure if we want to add the function to register concrete object here. Didn't we plan to register abstract shape only? Background/map class will keep and customize this shape.

---

*[docs/uml_src/UC_1_1.uml, line 19 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OoUGu6YigcTYVrC0W:-L0OoUGu6YigcTYVrC0X:bnj7hl0) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/docs/uml_src/UC_1_1.uml#L19)):*
> ```
> Map --> Map : create_background
> loop tiles
>   Map --> RenderingEngine : register_background
> ```

same as above

---

*[src/game/BoundaryWallsPositionsGenerator.cpp, line 10 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OqtCoABdeXb6kmJhP:-L0OqtCoABdeXb6kmJhQ:biibclj) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/src/game/BoundaryWallsPositionsGenerator.cpp#L10)):*
> else
>     {
This else is not necessary here. (Warning type: readability-else-after-return)

---

*[src/game/BoundaryWallsPositionsGenerator.cpp, line 16 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OrDe3B6jHqLrIIBi0:-L0OrDe4DFdzmVb7_eBQ:bkpifts) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/src/game/BoundaryWallsPositionsGenerator.cpp#L16)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>     {
>         return {{{0, 0}, {0, boundary_size}},
>                 {{0, 0}, {boundary_size, 0}},
>                 {{boundary_size, 0}, {boundary_size, boundary_size}},
>                 {{0, boundary_size}, {boundary_size, boundary_size}}};
</details>

I know that according to `modernize-return-braced-init-list` instead of `return Walls{...}` we can write `return {...}`, however in this form it loss readability for me.
Without looking into types declaration I thought it a list of walls that are constructed from two args: 1- position of wall, 2- vector that indicate the direction and length.

However, after I have looked at Wall declaration I have got confused. 
Using names to construct types may looks like it:
return  return {
                 Wall{PositionInSpace{0, 0},                        WallSize{0, boundary_size}},
                 Wall{PositionInSpace{0, 0},                        WallSize{boundary_size, 0}},
                 Wall{PositionInSpace{boundary_size, 0}, WallSize{boundary_size, boundary_size}},
                 Wall{PositionInSpace{0, boundary_size}, WallSize{boundary_size, boundary_size}}};

What is the interpretation of Wall if width is equal 0? (I assume the WallSize is constructed from {width, height}, am I wrong?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68)*

**Comment by kn65op** [comment]
Review status: 17 of 20 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/uml_src/class_diagram.uml, line 62 at r7](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L-bfZGJcwDP1xrc5aWV:-L0rxbqLBL0M53yO3e3P:b4c1r2a) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/02faf9dad424ff1a2134da19ee2104be879015b5/docs/uml_src/class_diagram.uml#L62)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I'm not sure if we want to add the function to register concrete object here. Didn't we plan to register abstract shape only? Background/map class will keep and customize this shape.
</blockquote></details>

Yes, it was added here, but notin code.
Done.

---

*[docs/uml_src/UC_1_1.uml, line 19 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OoUGu6YigcTYVrC0W:-L0rxmU2do58kU9ukMkv:btvlh0q) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/docs/uml_src/UC_1_1.uml#L19)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
Yes, it was added here, but not in code.

---

*[src/game/BoundaryWallsPositionsGenerator.cpp, line 10 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OqtCoABdeXb6kmJhP:-L0s4ctXxWriszBG8pmo:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/src/game/BoundaryWallsPositionsGenerator.cpp#L10)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

> else
>     {
This else is not necessary here. (Warning type: readability-else-after-return)

</blockquote></details>

Done.

---

*[src/game/BoundaryWallsPositionsGenerator.cpp, line 16 at r9](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68#-L0OrDe3B6jHqLrIIBi0:-L0s4e19-5g38-vEHz7j:bs7wumb) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/87cbe8ae880a2d8936e37be968ad915941895b8e/src/game/BoundaryWallsPositionsGenerator.cpp#L16)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

>     {
>         return {{{0, 0}, {0, boundary_size}},
>                 {{0, 0}, {boundary_size, 0}},
>                 {{boundary_size, 0}, {boundary_size, boundary_size}},
>                 {{0, boundary_size}, {boundary_size, boundary_size}}};

I know that according to `modernize-return-braced-init-list` instead of `return Walls{...}` we can write `return {...}`, however in this form it loss readability for me.
Without looking into types declaration I thought it a list of walls that are constructed from two args: 1- position of wall, 2- vector that indicate the direction and length.

However, after I have looked at Wall declaration I have got confused. 
Using names to construct types may looks like it:
return  return {
                 Wall{PositionInSpace{0, 0},                        WallSize{0, boundary_size}},
                 Wall{PositionInSpace{0, 0},                        WallSize{boundary_size, 0}},
                 Wall{PositionInSpace{boundary_size, 0}, WallSize{boundary_size, boundary_size}},
                 Wall{PositionInSpace{0, boundary_size}, WallSize{boundary_size, boundary_size}}};

What is the interpretation of Wall if width is equal 0? (I assume the WallSize is constructed from {width, height}, am I wrong?)

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68)*

**Comment by Abergard** [comment]
Reviewed 1 of 7 files at r9, 7 of 7 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68)*

**Comment by Abergard** [comment]
Reviewed 5 of 5 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/68)*

**Pull request merged**
