### PR TITLE
Adding class GameWordl

### PR DESCRIPTION
**Pull request by moose-x86**
For without uts because there is nothing really in this class.

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/65)

### CODE REVIEW

**Comment by kn65op** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/BombermanGameWorld.cpp, line 6 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65#-Ksr0Z6Ga8HldwJP4Cqt:-Ksr0Z6Ga8HldwJP4Cqu:boi5r5w) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0ab1ac227b2b98dcba9e98afc1269d01822abed1/src/game/BombermanGameWorld.cpp#L6)):*
> ```cpp
> bool BombermanGameWorld::is_bomb_at_pos(const BombPosition&) const
> {
>     return true;
> ```

Please write some logic

---

*[src/game/BombermanGameWorld.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65#-Ksr0xKHc3Vn7tFJw3b_:-Ksr0xKHc3Vn7tFJw3ba:b-cd0wv) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0ab1ac227b2b98dcba9e98afc1269d01822abed1/src/game/BombermanGameWorld.hpp#L21)):*
> ```cpp
>     virtual void update(ElapsedTime) override;
> 
> private:
> ```

In class diagram GameWorld also have bomberman

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by Abergard** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by moose-x86** [comment]
*[src/game/BombermanGameWorld.hpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65#-Ksr0xKHc3Vn7tFJw3b_:-Ksr5ZYCOTd03O1n3SVI:b-c9bvjv) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0ab1ac227b2b98dcba9e98afc1269d01822abed1/src/game/BombermanGameWorld.hpp#L21)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

In class diagram GameWorld also have bomberman
</blockquote></details>

bomberman can be loaded to entity vector. Gameworld don't need to know about bimberman.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by moose-x86** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/BombermanGameWorld.cpp, line 6 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65#-Ksr0Z6Ga8HldwJP4Cqt:-Ksr3pX88Cx4mPRdWzVo:bs7wunf) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0ab1ac227b2b98dcba9e98afc1269d01822abed1/src/game/BombermanGameWorld.cpp#L6)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Please write some logic
</blockquote></details>

Done.2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by moose-x86** [comment]
Reviewed 1 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by moose-x86** [comment]
Reviewed 10 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65)*

**Comment by kn65op** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/65#-:-Ksr8Mpl6GWBAyaa3hH-:bnfp4nl)*

**Pull request merged**
