### PR TITLE
Add LimitedBombLuncher - Fix #24 Fix #25

### LINKED ISSUE #24: create implementation BombLauncher

### LINKED ISSUE #25: create interface BombLauncher

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/74)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 1 of 8 files at r1, 3 of 89 files at r2, 3 of 6 files at r3.
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/game/BombLauncher.hpp, line 10 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4IQHaeWagi1On2ZKnw:-L4IQHaeWagi1On2ZKnx:b-v2zjft) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/game/BombLauncher.hpp#L10)):*
> ```cpp
>     virtual ~BombLauncher() noexcept = default;
> 
>     virtual bool try_spawn_bomb(const math::Position2f) = 0;
> ```

Please remove const or add reference.

---

*[src/game/LimitedBombLauncher.cpp, line 23 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4ISUz-usARVPcfzdrC:-L4ISUz-usARVPcfzdrD:bioqvc8) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/game/LimitedBombLauncher.cpp#L23)):*
> ```cpp
> bool LimitedBombLauncher::can_spawn_bomb(const math::Position2f pos) const
> {
>     return max_bombs > bombs && !game_world->is_bomb_at_pos(BombPosition{pos});
> ```

I am starting consider if creating structure inherit from math in that way is a good idea. We have WallPosition, ExplosionPosition, BombPosition. Why do we have so many kind of position when everything is laying on the same space / position. Shouldn't we have one type e.g. WorldPosition?

---

*[src/math/includes/math/Position2f.hpp, line 23 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4IS09IStyqBf4q5HDP:-L4IS09IStyqBf4q5HDQ:b-r1yhsa) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/math/includes/math/Position2f.hpp#L23)):*
>   constexpr Position2f(const Position2f&) = default;
>     constexpr Position2f(Position2f&&) = default;
>     constexpr Position2f& operator=(const Position2f&) = default;
>   
According to rules of five (https://i.stack.imgur.com/b2VBV.png) shouldn't this operators be declared by default?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74)*

**Comment by Abergard** [comment]
Reviewed 2 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/74)*

**Comment by kn65op** [comment]
Review status: 7 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/game/BombLauncher.hpp, line 10 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4IQHaeWagi1On2ZKnw:-L4pz-CLVxPjo1SbTCOI:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/game/BombLauncher.hpp#L10)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Please remove const or add reference.
</blockquote></details>

Done.

---

*[src/game/LimitedBombLauncher.cpp, line 23 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4ISUz-usARVPcfzdrC:-L4pz-dxv2j_0Lgv0e7C:b-35b3wq) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/game/LimitedBombLauncher.cpp#L23)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I am starting consider if creating structure inherit from math in that way is a good idea. We have WallPosition, ExplosionPosition, BombPosition. Why do we have so many kind of position when everything is laying on the same space / position. Shouldn't we have one type e.g. WorldPosition?
</blockquote></details>

I just used it.
Maybe no, but there is no WalPosition.Can be discussed.

---

*[src/math/includes/math/Position2f.hpp, line 23 at r3](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74#-L4IS09IStyqBf4q5HDP:-L4pzmcxjeQi5MCbr__4:b-ea01f8) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/98e67f25fb07706e3b9eaede04111a600b209050/src/math/includes/math/Position2f.hpp#L23)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

>   constexpr Position2f(const Position2f&) = default;
>     constexpr Position2f(Position2f&&) = default;
>     constexpr Position2f& operator=(const Position2f&) = default;
>   
According to rules of five (https://i.stack.imgur.com/b2VBV.png) shouldn't this operators be declared by default?
</blockquote></details>

Yes, forgot to remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74)*

**Comment by Abergard** [comment]
Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/74)*

**Pull request merged**
