### PR TITLE
Fix #76 - add missing functionalities in TimeBomb and LimitedBombLauncher

### LINKED ISSUE #76: Fix missing TimeBomb and LimitedBombLauncher functionality
LimitedBombLauncher shuold create Bomb
LimitedBombLauncher should register Bomb to GameWorld

Bomb should register itself to Physics and Render Engines
Bomb should notify LimitedBombLauncher about explosion.
Bomb should notify GameWorld about explosion
Bomb should deregister from Physics and Render Engines after explosion.
Bomb should create explosion when explodes.
Bomb should register explosion in GameWorld

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)

### CODE REVIEW

**Comment by Abergard** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/game/LimitedBombLauncher.ut.cpp, line 31 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L4r5bIXFeZ49syVLop2:-L4r5bIXFeZ49syVLop3:b2k9f5o) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/984cccddf8655d58708078e9f706fc736fe19ea0/src/game/LimitedBombLauncher.ut.cpp#L31)):*
>   std::shared_ptr<GameWorld> gw =
>         std::shared_ptr<GameWorld>(&game_world.get(), [](...) {});

Why doesn't you use Fake(Dtor(mock)) here?
It may looks like that:

In constructor:
        Fake(Dtor(game_world));
        Fake(Dtor(bomb_factory));

And shared_ptr initialization:
    std::shared_ptr<GameWorld> gw{&game_world.get()};
    std::shared_ptr<BombFactory> bf{&bomb_factory.get()};

Also, please move GameWorld's destructor from 21 line to 14 (to be at the top of class).
Don't ask why, just do it. I don't know why it helps yet, but helps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78)*

**Comment by Abergard** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/DefaultBombFactory.hpp, line 8 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L4rN6Lq2cFeW-TGJ3Yi:-L4rN6Lq2cFeW-TGJ3Yj:bh7p8yk) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/984cccddf8655d58708078e9f706fc736fe19ea0/src/game/DefaultBombFactory.hpp#L8)):*
> ```cpp
> {
> public:
>     virtual std::shared_ptr<Bomb> create_time_bomb() const = 0;
> ```

Why not unique_ptr? Are we planning to create only shared bombs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/game/DefaultBombFactory.hpp, line 8 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L4rN6Lq2cFeW-TGJ3Yi:-L6VfP1-hberbhmBP8uM:b-z2xtq3) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/984cccddf8655d58708078e9f706fc736fe19ea0/src/game/DefaultBombFactory.hpp#L8)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why not unique_ptr? Are we planning to create only shared bombs?
</blockquote></details>

Typo.

---

*[src/game/LimitedBombLauncher.ut.cpp, line 31 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L4r5bIXFeZ49syVLop2:-L6VfS1fN60gusqO4DC8:b-7s7li4) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/984cccddf8655d58708078e9f706fc736fe19ea0/src/game/LimitedBombLauncher.ut.cpp#L31)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

>   std::shared_ptr<GameWorld> gw =
>         std::shared_ptr<GameWorld>(&game_world.get(), [](...) {});

Why doesn't you use Fake(Dtor(mock)) here?
It may looks like that:

In constructor:
        Fake(Dtor(game_world));
        Fake(Dtor(bomb_factory));

And shared_ptr initialization:
    std::shared_ptr<GameWorld> gw{&game_world.get()};
    std::shared_ptr<BombFactory> bf{&bomb_factory.get()};

Also, please move GameWorld's destructor from 21 line to 14 (to be at the top of class).
Don't ask why, just do it. I don't know why it helps yet, but helps.
</blockquote></details>

No, I need to make shared_ptr to not delete memory.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78)*

**Comment by Abergard** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/DefaultBombFactory.cpp, line 7 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L6YFt2-tvldikAbaSzA:-L6YFt20Jn28KBHJcd6_:b4zvs9m) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/84bd53ab0626372a94b43b410a3ddf8dba950813/src/game/DefaultBombFactory.cpp#L7)):*
> ```cpp
> std::unique_ptr<Bomb> DefautlBombFactory::create_time_bomb() const
> {
>     return nullptr;
> ```

Will the TimeBomb be returned here later or have you just forgotten about it?

---

*[src/game/LimitedBombLauncher.cpp, line 32 at r2](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78#-L6YH8600pHGxfPQiG9O:-L6YH8600pHGxfPQiG9P:b-isejgy) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/84bd53ab0626372a94b43b410a3ddf8dba950813/src/game/LimitedBombLauncher.cpp#L32)):*
> ```cpp
> {
>     ++bombs;
>     bomb_factory->create_time_bomb();
> ```

Why bombs are not keep anywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/78)*

**Comment by Abergard** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)*

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @Abergard and @kn65op)

___
*[src/game/DefaultBombFactory.cpp, line 7 at r2](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-L6YFt2-tvldikAbaSzA:-LJSgOu-BE0_37_zOmAJ:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/84bd53ab0626372a94b43b410a3ddf8dba950813/src/game/DefaultBombFactory.cpp#L7)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Will the TimeBomb be returned here later or have you just forgotten about it?
</blockquote></details>

Done.
___
*[src/game/LimitedBombLauncher.cpp, line 32 at r2](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-L6YH8600pHGxfPQiG9O:-LARkk-l7v6eAJlGScEF:b118tqk) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/84bd53ab0626372a94b43b410a3ddf8dba950813/src/game/LimitedBombLauncher.cpp#L32)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why bombs are not keep anywhere?
</blockquote></details>

It is now.

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 13 of 16 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: all files reviewed, 3 unresolved discussions (waiting on @kn65op)

___
*[src/game/DefaultBombFactory.hpp, line 25 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJSrgPTEQEFwxR1Knyc:-LJSrgPTEQEFwxR1Knyd:bbi3xuw) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/53a5d39d531aad5c290d9c7a8df0452f7b349abd/src/game/DefaultBombFactory.hpp#L25)):*
> ```cpp
> 
> private:
>     physics::PhysicsEngine& physics_engine;
> ```

Do we want to make an assumption that physics engine and renderer pool will be always live longer than Factory?
___
*[src/game/TimeBomb.hpp, line 36 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJSscWj8dEhKo6yqJhO:-LJSscWj8dEhKo6yqJhP:bqhapsh) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/53a5d39d531aad5c290d9c7a8df0452f7b349abd/src/game/TimeBomb.hpp#L36)):*
> ```
>  bool shouldExplode() const;
>     void updateElapsedTime(DeltaTime);
>     void explode();
> ```

Please keep the functions above variables
___
*[src/game/TimeBomb.cpp, line 44 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJStTIdBO-bpT0cVPHk:-LJStTIeBkWX3OHkl15R:bjjdd9i) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/53a5d39d531aad5c290d9c7a8df0452f7b349abd/src/game/TimeBomb.cpp#L44)):*
> ```cpp
> bool TimeBomb::areYouDead() const
> {
>     return false;
> ```

Do you remember what should be returned here? Isn't connected with the 'exploded' value?

**Review by Abergard — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: all files reviewed, 3 unresolved discussions (waiting on @kn65op)

**Review by kn65op — COMMENTED** [review]
> Reviewed 13 of 16 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: 8 of 19 files reviewed, 3 unresolved discussions (waiting on @Abergard and @kn65op)

___
*[src/game/DefaultBombFactory.hpp, line 25 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJSrgPTEQEFwxR1Knyc:-LY66xXS3RWh4H3D5Nzs:b3m8jf) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/5ddb06de411b192fae45ace6af017e9b361989ad/src/game/DefaultBombFactory.hpp#L25)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Do we want to make an assumption that physics engine and renderer pool will be always live longer than Factory?
</blockquote></details>

I remeber that when I wrote this code engine and pool was always passed by ref.
I can change it.
___
*[src/game/TimeBomb.hpp, line 36 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJSscWj8dEhKo6yqJhO:-LY66nvU1F3I1vJUexfp:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/5ddb06de411b192fae45ace6af017e9b361989ad/src/game/TimeBomb.hpp#L36)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

> ```
>  bool shouldExplode() const;
>     void updateElapsedTime(DeltaTime);
>     void explode();
> ```

Please keep the functions above variables
</blockquote></details>

Done.
___
*[src/game/TimeBomb.cpp, line 44 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJStTIdBO-bpT0cVPHk:-LY66q510NZa7Sk9mLE5:b39a3pl) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/5ddb06de411b192fae45ace6af017e9b361989ad/src/game/TimeBomb.cpp#L44)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Do you remember what should be returned here? Isn't connected with the 'exploded' value?
</blockquote></details>

hasExploded is used to tell if bomb already exploded.

**Review by Abergard — COMMENTED** [review]
> Reviewed 12 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op)

___
*[src/game/TimeBomb.cpp, line 44 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJStTIdBO-bpT0cVPHk:-LYOHRfK45DIxT4If7Pn:bg0nr57) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/5ddb06de411b192fae45ace6af017e9b361989ad/src/game/TimeBomb.cpp#L44)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

hasExploded is used to tell if bomb already exploded.
</blockquote></details>

I can not find any information about ```areYouDead``` and ```hasExploded``` function in our design doc. After explosion the bomb should be removed, so who will be use this two functions?

**Review by Abergard — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-:-LYOJ1eTDcj1siU5XxRv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op)

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard)

___
*[src/game/TimeBomb.cpp, line 44 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/78#-LJStTIdBO-bpT0cVPHk:-LZE0B0M5f--6zB1gCvV:bvzrv5v) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/5ddb06de411b192fae45ace6af017e9b361989ad/src/game/TimeBomb.cpp#L44)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I can not find any information about ```areYouDead``` and ```hasExploded``` function in our design doc. After explosion the bomb should be removed, so who will be use this two functions?
</blockquote></details>

Bombas and explosion are stored in GameWorld as unique_ptr, so the best place to check this is game world.
I suppose this should be part of main loop.

**Pull request merged**
