### PR TITLE
Td/issue36 37

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/53)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/TimeBomb.cpp, line 29 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53#-KlG1MtPot-sml49DhU6:-KlG1MtQGZ0eu8qA8Ohf:b-opwfjo) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9bef2c502e32cb3bbe2138daaa40765ea19426f1/src/game/TimeBomb.cpp#L29)):*
> ```cpp
> bool TimeBomb::areYouDead() const
> {
>     return false;
> ```

Why is it always false? Shouldn't we return true if bomb has been destroyed?

---

*[src/game/TimeBombTest.cpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53#-KlG0VHBQAnefHI5ST20:-KlG0VHCzVwEx-gRvrvN:bas5svy) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9bef2c502e32cb3bbe2138daaa40765ea19426f1/src/game/TimeBombTest.cpp#L21)):*
> ```cpp
> {
>     using namespace std::chrono_literals;
>     bomb.update(1ms);
> ```

Haven't you forgotten to use bomb.hasExpleded()?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/TimeBomb.cpp, line 29 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53#-KlG1MtPot-sml49DhU6:-KnodvU4e1d4YnA67-Rb:b-5p1dje) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9bef2c502e32cb3bbe2138daaa40765ea19426f1/src/game/TimeBomb.cpp#L29)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why is it always false? Shouldn't we return true if bomb has been destroyed?
</blockquote></details>

bomb has hasExploded function to indicate that exploded

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53)*

**Comment by kn65op** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/game/TimeBombTest.cpp, line 21 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53#-KlG0VHBQAnefHI5ST20:-Knog8JxPzGpX7t4XaIT:bs7wumb) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9bef2c502e32cb3bbe2138daaa40765ea19426f1/src/game/TimeBombTest.cpp#L21)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Haven't you forgotten to use bomb.hasExpleded()?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53)*

**Comment by Abergard** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/53)*

**Pull request merged**
