### PR TITLE
Very little delta doesn't accumulate

### PR DESCRIPTION
**Pull request by Abergard**
Delta smaller than one millisecond was truncated to zero. The root cause was std::chrono::duration_cast<std::chrono::milliseconds> because std::chrono::milliseconds is a integer type.

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)

### CODE REVIEW

**Review by kn65op — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-:-LakyoFb1wAg2D-VdR_E:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @kn65op)

___
*[src/game/TimeBomb.hpp, line 40 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakxiTCDpCdXPXGymWk:-LakxiTCDpCdXPXGymWl:baxu9u4) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.hpp#L40)):*
> ```cpp
>     physics::PhysicsId physics_id;
>     graphics::renderer_id renderer_id;
>     std::chrono::duration<float> timeElapsed{};
> ```

Maybe change to DeltaTime?
___
*[src/game/TimeBomb.ut.cpp, line 123 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakyPWB7-bQNgs1bc2J:-LakyPWB7-bQNgs1bc2K:b-27prrp) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.ut.cpp#L123)):*
> ```cpp
> }
> 
> TEST_F(TimeBombTest, VeryLittleDelta_shouldAccumulate)
> ```

It passed once in CI with broken code. Consider change test to fail always with old code.

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @kn65op)

___
*[src/game/TimeBomb.ut.cpp, line 123 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakyPWB7-bQNgs1bc2J:-Lakyy9S3zxJyv9PC1Db:bazaem5) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.ut.cpp#L123)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

It passed once in CI with broken code. Consider change test to fail always with old code.
</blockquote></details>

https://travis-ci.org/NadzwyczajnaGrupaRobocza/bomberman/builds/510145769?utm_source=github_status&utm_medium=notification

**Review by kn65op — APPROVED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Abergard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/game/TimeBomb.hpp, line 40 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakxiTCDpCdXPXGymWk:-Lal7GNL07YQl04F-eiw:bl4h7j6) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.hpp#L40)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Maybe change to DeltaTime?
</blockquote></details>

Imho delta time refers to amount of time past between frames. If we want to change type here I would prefer to create another type for it eg. Time.
___
*[src/game/TimeBomb.ut.cpp, line 123 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakyPWB7-bQNgs1bc2J:-Lal8ytT2vd7lFHaB_fJ:bohqjci) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.ut.cpp#L123)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

https://travis-ci.org/NadzwyczajnaGrupaRobocza/bomberman/builds/510145769?utm_source=github_status&utm_medium=notification
</blockquote></details>

I couldn't found the CI job that succeeded with broken code. The link above is from commit which contain fix.
I made two commit, which the first one added only test   We can see that the test failed: : https://travis-ci.org/NadzwyczajnaGrupaRobocza/bomberman/builds/510145062.

**Review by kn65op — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard)

___
*[src/game/TimeBomb.hpp, line 40 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakxiTCDpCdXPXGymWk:-Laps123EjqXFo3sjYtK:b-5dke01) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.hpp#L40)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Imho delta time refers to amount of time past between frames. If we want to change type here I would prefer to create another type for it eg. Time.
</blockquote></details>

Time is bad name for storing time difference. DeltaTime is fine for me, but you may try with TimeDifference
___
*[src/game/TimeBomb.ut.cpp, line 123 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakyPWB7-bQNgs1bc2J:-LapsNbB9QDqEXO5VkSS:b-xpuit8) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.ut.cpp#L123)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I couldn't found the CI job that succeeded with broken code. The link above is from commit which contain fix.
I made two commit, which the first one added only test   We can see that the test failed: : https://travis-ci.org/NadzwyczajnaGrupaRobocza/bomberman/builds/510145062.
</blockquote></details>

Ok, seems it's incorrectly displayed in github

**Review by kn65op — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard)

**Review by Abergard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kn65op)

___
*[src/game/TimeBomb.hpp, line 40 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102#-LakxiTCDpCdXPXGymWk:-LaqT5H17HzZBBrqMxw4:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2014f7776ef336f6584aa6bbee297e3b5a107a59/src/game/TimeBomb.hpp#L40)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Time is bad name for storing time difference. DeltaTime is fine for me, but you may try with TimeDifference
</blockquote></details>

Done.

**Review by kn65op — APPROVED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/102)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
