### PR TITLE
Td/issue#29

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/57)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57#-KoRxcq08yCWTOzhL_--:-KoRxcq08yCWTOzhL_-0:bqdom5b) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/aed6a8424bdfa68c3d1f81232ab6078fe50a0c07/src/CMakeLists.txt#L4)):*
> ```CMake
> 
> add_subdirectory(graphics)
> set(GRAPHICS_INCLUDE_PATH ${CMAKE_CURRENT_LIST_DIR}/graphics)
> ```

What about "set(LIBS_INCLUDE_PATH ${CMAKE_CURRENT_LIST_DIR})"
Then every include from other modules will look like this "#include" module / file.hpp "

---

*[src/physics/PhysicsEngine.hpp, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57#-KoRytoTYl15vvDUufKR:-KoRytoTYl15vvDUufKS:b6488se) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/aed6a8424bdfa68c3d1f81232ab6078fe50a0c07/src/physics/PhysicsEngine.hpp#L16)):*
>  virtual void set_position(PhysicsId, const Position&) = 0;
>     virtual Position get_position(PhysicsId) const = 0;

Why not 'const PhysicsId' ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57)*

**Comment by kn65op** [comment]
Review status: 7 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/CMakeLists.txt, line 4 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57#-KoRxcq08yCWTOzhL_--:-KoiQf1gsFt6jNmCvkcZ:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9f6714c2085cc296eee5c001b8eac7efdfbcd694/src/CMakeLists.txt#L4)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

What about "set(LIBS_INCLUDE_PATH ${CMAKE_CURRENT_LIST_DIR})"
Then every include from other modules will look like this "#include" module / file.hpp "
</blockquote></details>

Done.

---

*[src/physics/PhysicsEngine.hpp, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57#-KoRytoTYl15vvDUufKR:-KoiQQXm133im6rbSRJo:b-20x1pc) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/9f6714c2085cc296eee5c001b8eac7efdfbcd694/src/physics/PhysicsEngine.hpp#L16)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

>  virtual void set_position(PhysicsId, const Position&) = 0;
>     virtual Position get_position(PhysicsId) const = 0;

Why not 'const PhysicsId' ?

</blockquote></details>

There is no point to add const, when passing by value in interface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57)*

**Comment by Abergard** [comment]
Reviewed 1 of 2 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57)*

**Comment by Abergard** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/57)*

**Pull request merged**
