### PR TITLE
Proposition of new file structures for docs

### PR DESCRIPTION
**Pull request by Abergard**
What about stop putting all diagrams/images to one directory, but using for each kind of diagrams a separate one?

---
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87)

### CODE REVIEW

**Review by kn65op — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87)* status: 0 of 55 files reviewed, 1 unresolved discussion (waiting on @Abergard, @kn65op, and @Feldmarszalekduda)

___
*[docs/design/SUMMARY.md, line 3 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87#-LSTULbO3PQisMXMP1hp:-LSTULbP2QpIIRpa_6Wc:b7vrfr7) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0331f7fd4245c8185ecfc3ddf7fa86a4a07f84e0/docs/design/SUMMARY.md#L3)):*
> ```Markdown
> # Summary
> 
> * [Domain model diagrams](01-DomainModel.md)
> ```

Consider put content of this file to README.md

**Review by kn65op — COMMENTED** [review]
> Reviewed 55 of 55 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard and @Feldmarszalekduda)

**Review by Abergard — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87)* status: 54 of 56 files reviewed, 1 unresolved discussion (waiting on @kn65op and @Feldmarszalekduda)

___
*[docs/design/SUMMARY.md, line 3 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87#-LSTULbO3PQisMXMP1hp:-LST_Ve3CfSECLaOCULx:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/0331f7fd4245c8185ecfc3ddf7fa86a4a07f84e0/docs/design/SUMMARY.md#L3)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Consider put content of this file to README.md
</blockquote></details>

Done.

**Review by kn65op — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87#-:-LZE6baOB_2CpBSbXIuI:bnfp4nl)* status: 54 of 60 files reviewed, all discussions resolved (waiting on @Feldmarszalekduda and @kn65op)

**Review by kn65op — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Feldmarszalekduda)

**Pull request merged**
