### PR TITLE
Updating README.md

### PR DESCRIPTION
**Pull request by Feldmarszalekduda**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)

### CODE REVIEW

**Review by Abergard — CHANGES_REQUESTED** [review]
Good job!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-:-LIRkl0I1IDYsk_hY6f5:b-ul7oqm)* status: all files reviewed, 3 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRerkX8dOo_s8hWbdW:-LIRerkY4VXou-tkJalS:b-91ehoz) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L26)):*
It can be written simpler
> ```
> git clone https://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
> ```
>  
> To get all external dependencies please run (this should be done only once for new repository):
> ```sh
> git submodule init
> git submodule update
> ```

This commands can be replaced by 
```
git clone https:://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
git submodule update --init
```
or even in one command
```
git clone --recurse-submodules -j <n> https://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
```
Where the <n> is the  number of submodules cloned in parallel
___
*[README.md, line 49 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRg_kqBu-WFcF147xT:-LIRg_kqBu-WFcF147xU:b1ptq7l) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L49)):*
Please consider using simpler and more generic commands not depending of the type of system. 

> ```
> Inside it create new directory (there will be placed files created during compilation):
> ```sh
> mkdir build
> ```
>  
> Go to this new dir:
> ```sh
> cd build
> ```
>  
> Inside please run cmake:
> ```sh
> cmake ..
> ```
>  
> After cmake finish creating files You can run compilation:
> ```sh
> make target
> ```

E.g to create project
```
cd bomberman
cmake -Bbuild .
```
to build all target
```
cmake --build build/
```
or to build specific target
```
cmake --build build/ --target <target>
```
___
*[README.md, line 57 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRiMSz2dKVVOLrRxlw:-LIRiMSz2dKVVOLrRxlx:b-tnwvld) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L57)):*
> ```Markdown
> If You want to recompile Your code, You should simply run make command:
> ```sh
> make target
> ```

Do not depend on `make` command.  The build system may be differ in many system. Some one can use `make`, someone else may prefer the  `ninja` or`msbuild` etc.
The better way is let cmake choose it.
```
cmake --build <build directory> --target <target>
````

**Review by Abergard — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 3 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRerkX8dOo_s8hWbdW:-LIRl2Wu1Qk47eAmkbNk:b-9qk4ki) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L26)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

It can be written simpler
> ```
> git clone https://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
> ```
>  
> To get all external dependencies please run (this should be done only once for new repository):
> ```sh
> git submodule init
> git submodule update
> ```

This commands can be replaced by 
```
git clone https:://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
git submodule update --init
```
or even in one command
```
git clone --recurse-submodules -j <n> https://github.com/NadzwyczajnaGrupaRobocza/bomberman.git
```
Where the <n> is the  number of submodules cloned in parallel
</blockquote></details>

Where the `<n>` is the number of submodules cloned in parallel*

**Review by kn65op — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 5 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[README.md, line 15 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LItQL6x4nBMkLn1hKXh:-LItQL6x4nBMkLn1hKXi:bf2byzd) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L15)):*
> ```Markdown
> - sfml (we are using version 2.5)
> 
> 1.2 Downloading and compiling code
> ```

Please add info how to run code.
___
*[README.md, line 71 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LItQG1J8VE8ftVRcrDK:-LItQG1J8VE8ftVRcrDL:b-k58bc6) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L71)):*
> ```Markdown
> 2.2 Making changes in code
> -------------------------------------------
> All updates should be done on dedicated branch, so please don't use master for changes. After cloning repository create Your branch and switch to it. After Your changes are ready You can push them.
> ```

Master is blocked for not administrators, we can add this info.

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 5 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[README.md, line 15 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LItQL6x4nBMkLn1hKXh:-LItQhRT1Rv89EtOGsLB:br88if3) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L15)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Please add info how to run code.
</blockquote></details>

How to test code*

**Review by Feldmarszalekduda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @Abergard, @kn65op, and @Feldmarszalekduda)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRerkX8dOo_s8hWbdW:-LItQ45P-30LWiajColc:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L26)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Where the <n> is the number of submodules cloned in parallel*
</blockquote></details>

Done.
___
*[README.md, line 49 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRg_kqBu-WFcF147xT:-LItQ5x31zCeZyXr-ecP:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L49)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Please consider using simpler and more generic commands not depending of the type of system. 

> ```
> Inside it create new directory (there will be placed files created during compilation):
> ```sh
> mkdir build
> ```
>  
> Go to this new dir:
> ```sh
> cd build
> ```
>  
> Inside please run cmake:
> ```sh
> cmake ..
> ```
>  
> After cmake finish creating files You can run compilation:
> ```sh
> make target
> ```

E.g to create project
```
cd bomberman
cmake -Bbuild .
```
to build all target
```
cmake --build build/
```
or to build specific target
```
cmake --build build/ --target <target>
```

</blockquote></details>

Done.
___
*[README.md, line 57 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LIRiMSz2dKVVOLrRxlw:-LItR4mLA64QJofOfOeh:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L57)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Do not depend on `make` command.  The build system may be differ in many system. Some one can use `make`, someone else may prefer the  `ninja` or`msbuild` etc.
The better way is let cmake choose it.
```
cmake --build <build directory> --target <target>
````
</blockquote></details>

Done.
___
*[README.md, line 71 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LItQG1J8VE8ftVRcrDK:-LItRY0u3Pb3Ov4OLTjS:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/ca54b08daf10a2d3095a9dc7de8d79811c32df15/README.md#L71)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Master is blocked for not administrators, we can add this info.
</blockquote></details>

Done.

**Review by Abergard — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 2 unresolved discussions (waiting on @kn65op and @Feldmarszalekduda)

**Review by kn65op — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 1 unresolved discussion (waiting on @Feldmarszalekduda)

**Review by Abergard — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 1 unresolved discussion (waiting on @Feldmarszalekduda)

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 2 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[README.md, line 79 at r4](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LKNY1my4fFh9puMcd3L:-LKNY1mzDzNPvhWnK7tn:b-3z4whl) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/f067a80e3411ba865e011744cde4335f0a3b5f80/README.md#L79)):*
> ```Markdown
> ...
> 
> # 2. How To Write And Make Changes
> ```

Please extract second part to CONTRIBUTING.md

**Review by Feldmarszalekduda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Abergard and @Feldmarszalekduda)

___
*[README.md, line 79 at r4](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LKNY1my4fFh9puMcd3L:-LK_ad9BC2ISssAZpHzX:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/f067a80e3411ba865e011744cde4335f0a3b5f80/README.md#L79)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Please extract second part to CONTRIBUTING.md
</blockquote></details>

Done.

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: all files reviewed, 2 unresolved discussions (waiting on @Feldmarszalekduda)

___
*[CONTRIBUTING.md, line 6 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LL60RgLEbA8Ibe3BkZ3:-LL60RgLEbA8Ibe3BkZ4:b-lp32l5) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/eba58c9b200b6a9383a2d42f78c5190d936e5934/CONTRIBUTING.md#L6)):*
> ```Markdown
> 
> - We are using snake_case for all names (variables, classes, functions, ...)
> - All code that You write should be covered by UTs. We are using TDD. Test are written in gtest, for mocking we are using fakeit.
> ```

typo, it should be "Tests are"
___
*[CONTRIBUTING.md, line 49 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LL6-YN17KI8yyN8TUmC:-LL6-YN17KI8yyN8TUmD:bqkdya3) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/eba58c9b200b6a9383a2d42f78c5190d936e5934/CONTRIBUTING.md#L49)):*
> ```Markdown
> ### 5.1 Creating pull request
> 
> After pushing changes go to Bomberman's github page and select Your repository. In riught top corner You should find green button "Create pull request"
> ```

typo, it should be "In the top right corner (...)"

**Review by Feldmarszalekduda — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Abergard)

___
*[CONTRIBUTING.md, line 6 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LL60RgLEbA8Ibe3BkZ3:-LL8__OVEeuooOhcmsbO:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/eba58c9b200b6a9383a2d42f78c5190d936e5934/CONTRIBUTING.md#L6)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

typo, it should be "Tests are"
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 49 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80#-LL6-YN17KI8yyN8TUmC:-LL8a_QbBRlNLvTg7Qjd:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/eba58c9b200b6a9383a2d42f78c5190d936e5934/CONTRIBUTING.md#L49)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

typo, it should be "In the top right corner (...)"
</blockquote></details>

Done.

**Review by Abergard — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/80)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
