### PR TITLE
Adding main p2

### PR DESCRIPTION
**Pull request by moose-x86**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84)

### CODE REVIEW

**Review by Abergard — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 6 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @moose-x86)

___
*[src/game/main.cpp, line 16 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84#-LIw5kvV5mTN8H3wYS8L:-LIw5kvV5mTN8H3wYS8M:biqff03) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/1fa153ca99f54a42b2740f71141ec74d0bb071a1/src/game/main.cpp#L16)):*
> ```cpp
>   sf::Window window(sf::VideoMode(window_size.width, window_size.height), "Bomberman Remake");
> 
>   //auto window = graphics::create_window(window_size, "Bomberman remake");
> ```

Why don't you use create_window function?

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84)* status: all files reviewed, 2 unresolved discussions (waiting on @moose-x86)

___
*[src/math/includes/math/Position2f.hpp, line 42 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84#-LIyx2IU4wodS23UbajY:-LIyx2IU4wodS23UbajZ:b-mecc2n) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/1fa153ca99f54a42b2740f71141ec74d0bb071a1/src/math/includes/math/Position2f.hpp#L42)):*
> ```cpp
> inline bool operator==(const Position2f& lhs, const Position2f& rhs)
> {
>     auto fequals = [](float a, float b, float ulp = 0) {
> ```

Ulp should not be 0

**Comment by moose-x86** [comment]
___
*[src/game/main.cpp, line 16 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84#-LIw5kvV5mTN8H3wYS8L:-LIzZynED0rfT7FK076w:b-u9va59) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/1fa153ca99f54a42b2740f71141ec74d0bb071a1/src/game/main.cpp#L16)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Why don't you use create_window function?
</blockquote></details>

Will do it after holiday.

**Comment by moose-x86** [comment]
___
*[src/math/includes/math/Position2f.hpp, line 42 at r5](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84#-LIyx2IU4wodS23UbajY:-LIz_8Dr7zg1wg6ctNNR:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/1fa153ca99f54a42b2740f71141ec74d0bb071a1/src/math/includes/math/Position2f.hpp#L42)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Ulp should not be 0
</blockquote></details>

Done.

**Review by Abergard — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84#-:-LIzcUK7EAuQzxCYlZoh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @moose-x86)

**Review by moose-x86 — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 6 files at r2, 3 of 3 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/84)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
