### PR TITLE
Update readme to latests changes in build system

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)

### CODE REVIEW

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op)

___
*[README.md, line 14 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100#-LaZTpFA1Qo7kbP5xHzC:-LaZTpFA1Qo7kbP5xHzD:b-l1bc8x) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/51d4908056053c9b1be72b743baff9668096cca7/README.md#L14)):*
> ```Markdown
> - cmake
> - boost
> - sfml (we are using version 2.5.1)
> ```

We need to change sfml version from 2.5.0 to 2.5.1 for appveyor CI first.
Morover, do we want to edit this readme every time the minor version of sfml is changed. Maybe it will be sufficient to note here information about major version e.i. "2.5.x"?

**Review by Abergard — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: all files reviewed, 2 unresolved discussions (waiting on @kn65op)

___
*[.appveyor.yml, line 28 at r2](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100#-LaZsfXB00pGxWMuQxHG:-LaZsfXB00pGxWMuQxHH:bh2qf6b) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/d4a1fc3beddcd651092e25a252fba358acb891b2/.appveyor.yml#L28)):*
> ```
>   - set SFML_URL="https://www.sfml-dev.org/files/SFML-2.5.0-windows-vc15-64-bit.zip"
> ```
You have forgotten to change this line. Here you have link to newer version: https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Abergard and @kn65op)

___
*[README.md, line 14 at r1](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100#-LaZTpFA1Qo7kbP5xHzC:-LaZuDEi3_Uto3u75RvQ:bzbcx5e) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/51d4908056053c9b1be72b743baff9668096cca7/README.md#L14)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

We need to change sfml version from 2.5.0 to 2.5.1 for appveyor CI first.
Morover, do we want to edit this readme every time the minor version of sfml is changed. Maybe it will be sufficient to note here information about major version e.i. "2.5.x"?
</blockquote></details>

Since 2.5.0 will not compile we need to state 2.5.1 is minimum version

**Review by Abergard — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op)

**Review by Abergard — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100#-:-La_1uxgB4cjbaI7kX2-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kn65op)

**Review by kn65op — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: all files reviewed, 1 unresolved discussion (waiting on @Abergard)

___
*[.appveyor.yml, line 28 at r2](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100#-LaZsfXB00pGxWMuQxHG:-La_G1-0E4HYjflJRvgq:bs7wumb) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/d4a1fc3beddcd651092e25a252fba358acb891b2/.appveyor.yml#L28)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

> ```
>   - set SFML_URL="https://www.sfml-dev.org/files/SFML-2.5.0-windows-vc15-64-bit.zip"
> ```
You have forgotten to change this line. Here you have link to newer version: https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
</blockquote></details>

Done.

**Review by Abergard — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/100)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
