### PR TITLE
Improve coverage fot UT physics engine

### PR DESCRIPTION
**Pull request by kn65op**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/71)

### CODE REVIEW

**Comment by Abergard** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/physics/PhysicsEngine.ut.cpp, line 81 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71#-L3gAlprpQpDFUkClCcs:-L3gAlprpQpDFUkClCct:btogmqp) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/93fd591042285f160987b5f0201576b5b16640ad/src/physics/PhysicsEngine.ut.cpp#L81)):*
> ```cpp
> }
> 
> TEST_F(PhysicsEngineInterfaceTest, ShouldHaveDeegisterColiderFunction)
> ```

Only misspelling. Should be '...Deregister...' not '...Deegister...'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71)*

**Comment by Abergard** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/physics/PhysicsEngine.ut.cpp, line 81 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71#-L3gAlprpQpDFUkClCcs:-L4FJPz6b3bD0rV8Fjn3:bb71jbx) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/93fd591042285f160987b5f0201576b5b16640ad/src/physics/PhysicsEngine.ut.cpp#L81)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

Only misspelling. Should be '...Deregister...' not '...Deegister...'
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71)*

**Comment by Abergard** [comment]
Please revert submodule. If you want to upgrade it please do it in separately pull request.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71#-:-L4FOSPNTvvy9VqtykoL:b-tfw546)*

**Comment by Abergard** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/71)*

**Pull request merged**
