### PR TITLE
C++17

### PR DESCRIPTION
**Pull request by Abergard**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/69)

### CODE REVIEW

**Comment by kn65op** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/platforms/Windows.cmake, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69#-L-QcrgQa2bGYY2Uhig_:-L-QcrgQa2bGYY2Uhiga:b-4a771w) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a130658ab7adebad951ba1ad02c161dd63bcc0cf/cmake/platforms/Windows.cmake#L16)):*
> ```CMake
>   set(CMAKE_INCLUDE_SYSTEM_FLAG_CXX "/imsvc ")
>   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} \
>   -Xclang -std=c++1z")
> ```


Shouldn't we set 1z or 17 by compiler version, not platform?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/platforms/Windows.cmake, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69#-L-QcrgQa2bGYY2Uhig_:-L-QzPx3sFl-lXwBmdAT:bew29ao) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a130658ab7adebad951ba1ad02c161dd63bcc0cf/cmake/platforms/Windows.cmake#L16)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

Shouldn't we set 1z or 17 by compiler version, not platform?
</blockquote></details>

I agree that putting compilation flag to compiler file have more sense, however the kind of flag highly depend on the platform we use. Clang doesn't have own linker (what I know a 'lld' is not officially finished yet :( )
For Window we need to use -fms-compatibility to use appropriate visual's sdk version or explicitly mark argument as clang's argument (because on window we are using clang-cl, not clang) by passing a '-Xclang' before every command.
Imo the platform's cmake file is the easiest place to configure it for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/platforms/Windows.cmake, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69#-L-QcrgQa2bGYY2Uhig_:-L-R13xXQ6ekey3uX4FI:bcmku7e) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a130658ab7adebad951ba1ad02c161dd63bcc0cf/cmake/platforms/Windows.cmake#L16)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I agree that putting compilation flag to compiler file have more sense, however the kind of flag highly depend on the platform we use. Clang doesn't have own linker (what I know a 'lld' is not officially finished yet :( )
For Window we need to use -fms-compatibility to use appropriate visual's sdk version or explicitly mark argument as clang's argument (because on window we are using clang-cl, not clang) by passing a '-Xclang' before every command.
Imo the platform's cmake file is the easiest place to configure it for now.
</blockquote></details>

I do not insist to have it here. We can also move this part to Clang.cmake and add this flag only for 'if(${WIN32})' is satisfied.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69)*

**Comment by kn65op** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/platforms/Windows.cmake, line 16 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69#-L-QcrgQa2bGYY2Uhig_:-L-R1toJF-8ylNAi4iXw:b-9ie4b6) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/a130658ab7adebad951ba1ad02c161dd63bcc0cf/cmake/platforms/Windows.cmake#L16)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

I do not insist to have it here. We can also move this part to Clang.cmake and add this flag only for 'if(${WIN32})' is satisfied.
</blockquote></details>

OK for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/69)*

**Pull request merged**
