### PR TITLE
Human player

### PR DESCRIPTION
**Pull request by lukasz-m-maciejewski**
This change is [Reviewable](https://reviewable.io/reviews/nadzwyczajnagruparobocza/bomberman/52)

### CODE REVIEW

**Comment by kn65op** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/game/HumanPlayerSfml.cpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjse3z6hsB1iMQpEt2_:-Kjse3z6hsB1iMQpEt2a:b-sez6tp) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayerSfml.cpp#L7)):*
> HumanPlayerSfml::HumanPlayerSfml()
> {
> }
Looks like no need for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/game/HumanPlayerSfml.cpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjse3z6hsB1iMQpEt2_:-Kjse_8Sm22HVHAD2Ywc:bdaek36) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayerSfml.cpp#L7)):*
<details><summary><i>Previously, kn65op (Tomasz Drzewiecki) wrote…</i></summary><blockquote>

> HumanPlayerSfml::HumanPlayerSfml()
> {
> }
Looks like no need for this.
</blockquote></details>

good point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Comment by Abergard** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/game/HumanPlayer.hpp, line 13 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjsf0sPtLlEj7zu3-FF:-Kjsf0sPtLlEj7zu3-FG:b-mjndsl) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayer.hpp#L13)):*
> ```cpp
>     virtual ~HumanPlayer() = default;
> 
>     virtual VectorInt2D get_direction() = 0;
> ```

add const please

---

*[src/game/HumanPlayer.hpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjsf6ItjZiMBke68J2D:-Kjsf6ItjZiMBke68J2E:b-mjndsl) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayer.hpp#L14)):*
> ```cpp
> 
>     virtual VectorInt2D get_direction() = 0;
>     virtual bool wants_bomb() = 0;
> ```

add const please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Comment by Abergard** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/game/HumanPlayerSfml.hpp, line 10 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-KjsfYMqi-XvQOslBvJ3:-KjsfYMrN5WkiZaVkD6F:b-fr0h5l) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayerSfml.hpp#L10)):*
> ```cpp
>     HumanPlayerSfml();
> 
>     VectorInt2D get_direction();
> ```

add overrides please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Comment by lukasz-m-maciejewski** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/game/HumanPlayer.hpp, line 13 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjsf0sPtLlEj7zu3-FF:-KjsfnfgqIYxS6yZqt9B:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayer.hpp#L13)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

add const please
</blockquote></details>

Done.

---

*[src/game/HumanPlayer.hpp, line 14 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjsf6ItjZiMBke68J2D:-KjsfoEgivRVSer0LxeA:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayer.hpp#L14)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

add const please
</blockquote></details>

Done.

---

*[src/game/HumanPlayerSfml.cpp, line 7 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-Kjse3z6hsB1iMQpEt2_:-Kjsfq-aqFJ3cwtfZvX8:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayerSfml.cpp#L7)):*
<details><summary><i>Previously, lukasz-m-maciejewski (Łukasz Maciejewski) wrote…</i></summary><blockquote>

good point
</blockquote></details>

Done.

---

*[src/game/HumanPlayerSfml.hpp, line 10 at r1](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-KjsfYMqi-XvQOslBvJ3:-Kjsfs2zpHxqXvcD-Ddv:b-896fix) ([raw file](https://github.com/nadzwyczajnagruparobocza/bomberman/blob/2784d6662c7f9ba3f0f47918d6d893236d014864/src/game/HumanPlayerSfml.hpp#L10)):*
<details><summary><i>Previously, Abergard (Lukass) wrote…</i></summary><blockquote>

add overrides please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Comment by kn65op** [comment]
:lgtm:

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52#-:-KjsgSOur-iu8ujFQ2aC:bnfp4nl)*

**Comment by Abergard** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nadzwyczajnagruparobocza/bomberman/52)*

**Pull request merged**
